spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: wlx-backend-auth-service
          uri: lb://wlx-backend-auth-service
          predicates:
            - Path=/api/auth/**
        - id: wlx-backend-question-service
          uri: lb://wlx-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: wlx-backend-judge-service
          uri: lb://wlx-backend-judge-service
          predicates:
            - Path=/api/judge/**
        - id: wlx-backend-post-service
          uri: lb://wlx-backend-post-service
          predicates:
            - Path=/api/post/**
  application:
    name: wlx-backend-gateway
  main:
    web-application-type: reactive
  data:
    redis:
      database: 1
      host: localhost
      port: 6379
      timeout: 5000
server:
  port: 8101
knife4j:
  gateway:
    # 开启gateway聚合组件
    enabled: true
    # 使用手动聚合模式（因为服务有context-path）
    strategy: manual
    routes:
      - name: 题目服务
        url: /api/question/v3/api-docs
        service-name: wlx-backend-question-service
        order: 1
      - name: 判题服务
        url: /api/judge/v3/api-docs
        service-name: wlx-backend-judge-service
        order: 2
      - name: 帖子服务
        url: /api/post/v3/api-docs
        service-name: wlx-backend-post-service
        order: 3
      - name: 认证服务
        url: /api/auth/v3/api-docs
        service-name: wlx-backend-auth-service
        order: 4
white-list:
  urls:
    - /api/auth/user/login
    - /api/auth/user/register
    - /api/auth/wechat/**
    - /**/v3/api-docs
    - /api/post/comment/get/{id}
    - /api/post/getInfo/{id}
    - /api/post/page
    - /api/question/get/vo
    - /api/question/list/page/vo